#!/bin/sh

source /etc/dotfiles/bash-helpers/display.sh

export MONITOR=$(display_name)
export MONITORS=( $(display_name) )
MONITOR=${MONITOR:-${MONITORS[0]}}

if is_laptop_display; then
  bspc config window_gap 0
else
  bspc config window_gap 8
fi

bspc config borderless_monocle true
bspc config gapless_monocle true

bspc config border_width 2

bspc config normal_border_color "#131519"
bspc config active_border_color "#131519"
bspc config focused_border_color "#f0c674"

bspc monitor $MONITOR -d {1,2,3,4,5,6,7}

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

# Rules
bspc rule -r '*'

bspc rule -a SimpleScreenRecorder state=floating
bspc rule -a Spotify state=floating
bspc rule -a Emacs split_ratio=0.28 state=tiled state=tiled
bspc rule -a Emacs:doom-capture state=floating

bspc rule -a Chromium split_ratio=0.32 --center

bspc rule -a Pavucontrol state=floating
bspc rule -a mpv state=floating center=on
bspc rule -a Pinentry state=floating center=on
bspc rule -a GtkFileChooserDialog state=floating rectangle=300x300+190+134 --center --focus

bspc rule -a feh state=fullscreen
bspc rule -a st-scratch state=floating sticky=on center=on

for file in $XDG_CONFIG_HOME/bspwm/rc.d/*; do
  source "$file"
done
