#!/bin/sh

source /etc/dotfiles/bash-helpers/display.sh

export MONITOR=$(display_name)
export MONITORS=( $(display_name) )
MONITOR=${MONITOR:-${MONITORS[0]}}

if is_laptop_display; then
  bspc config window_gap 0
else
  bspc config window_gap 8
fi


# Only have workspaces for primary monitor
bspc monitor $MONITOR -d {1,2,3,4,5}

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true


# Rules
bspc rule -r '*'

bspc rule -a SimpleScreenRecorder state=floating
bspc rule -a Spotify state=floating
bspc rule -a 'Emacs:org*' state=floating
bspc rule -a 'Emacs:capture' state=floating
bspc rule -a mpv state=floating center=on
bspc rule -a Pinentry state=floating center=on
bspc rule -a Emacs split_ratio=0.23 border=off state=fullscreen
bspc rule -a Chromium split_ratio=0.32 --center
bspc rule -a feh state=fullscreen
bspc rule -a st-scratch state=floating sticky=on center=on


#
for file in $XDG_CONFIG_HOME/bspwm/rc.d/*; do
  source "$file"
done
