#!/bin/sh

bspc config borderless_monocle true
bspc config gapless_monocle true

bspc config border_width 2

bspc config normal_border_color "#131519"
bspc config active_border_color "#131519"
bspc config focused_border_color "#f0c674"
